Pin Node version in hopes it'll fix an error.
The error is:

```
FetchError: Invalid response body while trying to fetch https://accounts.muckrock.com/api/token/: Premature close
    at Gunzip.<anonymous> (/home/runner/work/nypd-docs/nypd-docs/node_modules/node-fetch/lib/index.js:400:12)
    at Gunzip.emit (node:events:521:24)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ERR_STREAM_PREMATURE_CLOSE',
  code: 'ERR_STREAM_PREMATURE_CLOSE'
}
```

https://github.com/nodejs/node/issues/63989 says this is an issue with Node 24.17.0 so this pins to 24.16 in hopes that GitHub Actions actually uses this and that this will fix the issue.